[package]
name = "mshdbg"
version = "0.1.0"
edition = "2021"

[dependencies]
lldb = "0.0.11"
eframe = { version = "0.29.1", features = [ "default" ] }
color-eyre = "0.6.3"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing-error = "0.2.0"
